Repository tasnimzotder/hacktoberfest-2021-little-steps, pull requests merged in 2021-10, with the labels that each got.

#7 update README & index.tsx theme name
  README.md
  pages/index.tsx
Labels: documentation 📃

#9 update homepage banner image
  README.md
  assets/banner_homepage.jpeg
Labels: documentation 📃, enhancement

#12 update README
  README.md
Labels: bug 🐛, documentation 📃

#11 Add New Post - pritambera2000
  md-posts/pritambera2000.md
  public/assets/md-images/ClimateChange.jpg
  public/assets/md-images/GreenHouse.jpeg
  public/assets/md-images/Industry.jpeg
  public/assets/md-images/PolarBear.jpeg
  public/assets/md-images/WorldHunger1.jpeg
  public/assets/md-images/WorldHunger2.jpeg
  public/assets/md-images/penguine.jpg
Labels: Hacktoberfest, md-posts

#13 Title Improved
  md-posts/pritambera2000.md
Labels: bug 🐛, Hacktoberfest

#15 Add a new post - calag4n
  md-posts/calag4n.md
Labels: Hacktoberfest, md-posts
